begin;
create extension if not exists pgtap with schema extensions;
select plan(28);

-- ---------------------------------------------------------------------------
-- The crawler's own daily spend ledger: one row per provider call, so that a DAY
-- has a ceiling and not merely a run.
--
-- Four things this file exists to hold still, because each one fails silently if
-- it drifts — and every one of them fails in the direction of a run that spends
-- more than it should:
--   * the grants. A public table is auto-granted to every Data API role, so the
--     revoke is the only thing between this ledger and the publishable key — and
--     `service_role`'s auto-grant is ALL. Neither DELETE nor UPDATE is granted
--     back here: a spend that can be removed or lowered is not evidence of
--     anything, and unlike the observation store there is no upsert to need it.
--   * `spent_on`, which is generated by exactly the expression
--     `availability_observations.observed_on` uses. The two are read side by
--     side; a day boundary that disagreed would charge a run's calls to a day
--     the observations do not believe it is in.
--   * the IST offset. 18:30Z is already the next IST day, and a UTC-derived day
--     would mis-bucket every call made after it.
--   * that two calls are two rows. The day's spend IS the row count, so anything
--     that collapsed duplicates would under-report the spend — the one direction
--     the whole design refuses.
--
-- NO PERSONAL DATA, and not even a journey: a row says only that one provider
-- call was spent at one moment. `columns_are` pins that.
-- ---------------------------------------------------------------------------

select has_table('public', 'crawler_provider_calls', 'the crawler spend ledger exists');

select columns_are(
  'public',
  'crawler_provider_calls',
  array['id', 'spent_at', 'spent_on'],
  'exactly these columns: a spend, and nothing about who or what it was spent on'
);

select col_is_pk('public', 'crawler_provider_calls', 'id', 'a spend is keyed by its own id');
select col_not_null('public', 'crawler_provider_calls', 'spent_at', 'a spend always says when it was made');
select col_not_null('public', 'crawler_provider_calls', 'spent_on', 'and the day it is charged to is always derivable');
select col_type_is('public', 'crawler_provider_calls', 'spent_at', 'timestamp with time zone', 'the moment is an instant, not a local time');
select col_type_is('public', 'crawler_provider_calls', 'spent_on', 'date', 'the day charged is a calendar date');

-- ---------------------------------------------------------------------------
-- Grants. Every line here asserts a revoke that had to be written by hand.
--
-- The `service_role` lines are not padding. Its auto-grant is ALL, which
-- includes UPDATE and DELETE — and this is the counter a scheduled crawler's
-- whole safety rests on. A counter the writer can reset is not a counter.
-- ---------------------------------------------------------------------------
select is(has_table_privilege('anon', 'public.crawler_provider_calls', 'select')::text, 'false', 'anon cannot read the crawler ledger');
select is(has_table_privilege('anon', 'public.crawler_provider_calls', 'insert')::text, 'false', 'anon cannot charge calls to it');
select is(has_table_privilege('anon', 'public.crawler_provider_calls', 'update')::text, 'false', 'anon cannot change it');
select is(has_table_privilege('anon', 'public.crawler_provider_calls', 'delete')::text, 'false', 'anon cannot erase a spend');
select is(has_table_privilege('authenticated', 'public.crawler_provider_calls', 'select')::text, 'false', 'a signed-in traveller cannot read the crawler ledger');
select is(has_table_privilege('authenticated', 'public.crawler_provider_calls', 'insert')::text, 'false', 'nor charge calls to it');
select is(has_table_privilege('authenticated', 'public.crawler_provider_calls', 'update')::text, 'false', 'nor change it');
select is(has_table_privilege('authenticated', 'public.crawler_provider_calls', 'delete')::text, 'false', 'nor erase a spend');
select is(has_table_privilege('service_role', 'public.crawler_provider_calls', 'select')::text, 'true', 'the crawler reads the day it is about to spend into');
select is(has_table_privilege('service_role', 'public.crawler_provider_calls', 'insert')::text, 'true', 'and charges each call as it goes');
select is(has_table_privilege('service_role', 'public.crawler_provider_calls', 'update')::text, 'false', 'a recorded spend can never be lowered, so nothing may update one');
select is(has_table_privilege('service_role', 'public.crawler_provider_calls', 'delete')::text, 'false', 'nor removed: a spend record that can be deleted proves nothing');

select is(
  (select relrowsecurity from pg_class where oid = 'public.crawler_provider_calls'::regclass)::text,
  'true',
  'row level security is enabled, as the second lock on the same door'
);
select is(
  (select count(*) from pg_policies where schemaname = 'public' and tablename = 'crawler_provider_calls'),
  0::bigint,
  'no policy opens the ledger to a Data API role'
);

-- The one read there is: how many calls has today already cost? It runs before
-- every run decides whether to start.
select has_index('public', 'crawler_provider_calls', 'crawler_provider_calls_day_idx', 'the day the count is taken over is indexed');

-- ---------------------------------------------------------------------------
-- `spent_on` is generated, and a caller cannot write it. A writable day column
-- is a budget a caller can charge to yesterday.
--
-- These two use a timestamp nothing below asks about: a `throws_ok` whose
-- statement stops throwing SUCCEEDS instead, leaving a row behind, and a stray
-- row breaks whatever counts rows later.
-- ---------------------------------------------------------------------------
select throws_ok(
  $$insert into public.crawler_provider_calls (spent_at, spent_on) values ('2026-01-01T00:00:00Z', '2026-01-01')$$,
  '428C9'::char(5),
  'cannot insert a non-DEFAULT value into column "spent_on"',
  'a caller cannot write the day its call is charged to'
);
select throws_ok(
  $$update public.crawler_provider_calls set spent_on = '2026-01-01' where spent_at = '2026-01-01T00:00:00Z'$$,
  '428C9'::char(5),
  'column "spent_on" can only be updated to DEFAULT',
  'nor move a spend to another day afterwards'
);

-- ---------------------------------------------------------------------------
-- The day is IST, and it is the SAME day boundary the observations use. 18:30Z
-- is already 2026-09-24 in India; a server that forgot the offset would charge
-- this call to the 23rd while the row it bought was filed under the 24th.
-- ---------------------------------------------------------------------------
insert into public.crawler_provider_calls (spent_at) values ('2026-09-23T18:30:00Z');

select is(
  (select spent_on from public.crawler_provider_calls where spent_at = '2026-09-23T18:30:00Z'),
  '2026-09-24'::date,
  'a call made at 18:30Z is charged to the next IST day, not the UTC one'
);

insert into public.availability_observations
  (observed_at, train_no, from_code, to_code, travel_class, quota, journey_date, status, can_book, raw_status)
values
  ('2026-09-23T18:30:00Z', '12621', 'MAS', 'NDLS', 'SL', 'GN', '2026-10-01', 'WAITLIST', true, 'GNWL65/WL26');

select is(
  (select spent_on from public.crawler_provider_calls where spent_at = '2026-09-23T18:30:00Z'),
  (select observed_on from public.availability_observations where observed_at = '2026-09-23T18:30:00Z'),
  'the spend and the row it bought agree on which day they belong to'
);

-- ---------------------------------------------------------------------------
-- Two calls are two rows. The day's spend is the row COUNT, so a unique index or
-- an upsert added here later would silently under-report — which is the one
-- direction this whole design refuses, because it under-reports precisely when
-- something has gone wrong.
-- ---------------------------------------------------------------------------
insert into public.crawler_provider_calls (spent_at) values ('2026-09-23T18:30:00Z');

select is(
  (select count(*)::int from public.crawler_provider_calls where spent_on = '2026-09-24'),
  2,
  'the same instant twice is two calls and two rows, because two calls were made'
);

-- Just before IST midnight is still the same day; a minute later is not.
insert into public.crawler_provider_calls (spent_at) values ('2026-09-24T18:29:59Z');

select is(
  (select count(*)::int from public.crawler_provider_calls where spent_on = '2026-09-24'),
  3,
  'a call at 23:59:59 IST is still charged to that day, so a late run does not borrow tomorrow'
);

select * from finish();
rollback;
