import { paxRows, type PaxRow } from "@/components/pnr/pnr-terminal-state";
import { messages } from "@/messages";
import { buildFixtureResult } from "@/services/sources/fixture";
import { formatTime } from "@/utils/datetime";
import { statusLabel } from "@/utils/status-tone";

// The specimen on Sheet 02 is generated by the labelled development fixture — the
// same pure generator the sample source serves — so it is design material that
// cannot drift from what the product actually renders. Imported only by the server
// page, so the fixture never ships in the client bundle.

export const SPECIMEN_PNR = "2345678909";

export interface Specimen {
  readonly leadTag: string;
  readonly trainLine: string;
  readonly journeyLine: string;
  readonly pax: readonly PaxRow[];
  readonly provenance: string;
}

export function buildSpecimen(now: Date): Specimen | null {
  const outcome = buildFixtureResult(SPECIMEN_PNR, now);
  if (!outcome.ok) return null;
  const { snapshot, lead, checkedAt } = outcome.result;
  const m = messages.home.record;
  const r = messages.check.result;
  return {
    leadTag: m.leadTag(statusLabel(lead.status, lead.position)),
    trainLine: m.trainLine(snapshot.train.number, snapshot.train.name ?? "", r.values.route(snapshot.train.from.code, snapshot.train.to.code)),
    journeyLine: m.journeyLine(snapshot.journeyDateLabel, snapshot.train.depTime ?? "", lead.quota),
    pax: paxRows(snapshot.pax),
    provenance: r.provenance.retrieved(formatTime(checkedAt), r.sources.fixture),
  };
}
