import { paxRows, statusCode, type PaxRow } from "@/components/pnr/pnr-terminal-state";
import { messages } from "@/messages";
import { buildFixtureResult } from "@/services/sources/fixture";
import { formatTime } from "@/utils/datetime";
import { formatPnr } from "@/utils/pnr";
import { statusLabel } from "@/utils/status-tone";

// The specimen on Sheet 02 is generated by the labelled development fixture — the
// same pure generator the sample source serves — so it is design material that
// cannot drift from what the product actually renders. Imported only by the server
// page, so the fixture never ships in the client bundle.

export const SPECIMEN_PNR = "2345678909";

export interface SpecimenSeats {
  readonly cls: string;
  readonly coach: string;
  readonly berth: string;
  readonly status: string;
  readonly waiting: readonly { readonly index: number; readonly label: string }[];
}

export interface Specimen {
  readonly leadTag: string;
  readonly trainLine: string;
  readonly journeyLine: string;
  readonly pax: readonly PaxRow[];
  readonly provenance: string;
  readonly seats: SpecimenSeats | null;
  readonly retrieved: string;
}

export function buildSpecimen(now: Date, pnr: string = SPECIMEN_PNR): Specimen | null {
  const outcome = buildFixtureResult(pnr, now);
  if (!outcome.ok) return null;
  const { snapshot, lead, checkedAt } = outcome.result;
  const m = messages.home.record;
  const r = messages.check.result;
  const waiting = snapshot.pax.filter((p) => !p.berth).map((p) => ({ index: p.index, label: statusCode(p.currentStatus, p.position) }));
  // The berth plan draws a 3A coach, so it shows only a lead with a berth in one.
  const seats = lead.coach && lead.berth && snapshot.cls === "3A" ? { cls: snapshot.cls, coach: lead.coach, berth: lead.berth, status: statusCode(lead.status, lead.position), waiting } : null;
  return {
    leadTag: m.leadTag(statusLabel(lead.status, lead.position)),
    trainLine: m.trainLine(snapshot.train.number, snapshot.train.name ?? "", r.values.route(snapshot.train.from.code, snapshot.train.to.code)),
    journeyLine: m.journeyLine(snapshot.journeyDateLabel, snapshot.train.depTime ?? "", lead.quota),
    pax: paxRows(snapshot.pax),
    provenance: r.provenance.retrieved(formatTime(checkedAt), r.sources.fixture),
    seats,
    retrieved: formatTime(checkedAt),
  };
}

/** What 02's chapters instrument prints about the specimen (spec ruling J3-11): its own PNR, statuses, party and
 * retrieval time, never retyped. */
export interface ChapterTrace {
  readonly pnr: string;
  readonly digits: string;
  readonly statuses: string;
  readonly party: readonly string[];
  readonly count: number;
  readonly retrieved: string;
}

export function chapterTrace(specimen: Specimen, pnr: string = SPECIMEN_PNR): ChapterTrace {
  const m = messages.journey;
  const seat = specimen.seats ? m.berths.seat(specimen.seats.coach, specimen.seats.berth) : null;
  return {
    pnr: formatPnr(pnr),
    digits: pnr,
    statuses: specimen.pax.map((p) => p.current.split(" ")[0]).join(" · "),
    party: specimen.pax.map((p, i) => m.chapters.party(i + 1, p.current, i === 0 ? seat : null)),
    count: specimen.pax.length,
    retrieved: specimen.retrieved,
  };
}
