import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "@/types/supabase";

// ---------------------------------------------------------------------------
// The availability crawler's DAILY budget: what the day has already cost the
// provider's plan, and what is therefore left for this run.
//
// `crawlCeiling` in `scripts/crawl-plan.mjs` is gate A, and it is per RUN. Two
// runs in one day spend twice the ceiling, because nothing remembers the first.
// A human running this and reading it could hold that fact in their head; a
// scheduler cannot, and a spent plan answers 429 — which rests the live PNR path
// too, whose `PNR_FALLBACK` is `none`. That rest is a traveller's final answer.
//
// The counter lives in Postgres and not in Upstash, for reasons the migration
// states in full: the crawler already requires this database and refuses to
// start without it, so the counter cannot be unavailable while the crawler can
// run; it is shared across machines; and `shared-store.ts`'s per-environment key
// prefix — which makes the existing usage counter useless here — does not arise.
//
// **The arithmetic is pure and the store access is not, and they are kept apart
// deliberately.** `dayCeiling` decides, from three numbers, and is proved
// without a database. Only the runner touches the world.
//
// No personal data: a row is a spend and nothing else. No PNR, no user, no
// train, no leg, not even the date that was asked for.
// ---------------------------------------------------------------------------

/** One row per provider call the crawler made. The day's spend is the row COUNT; see the migration. */
export const CRAWLER_CALL_TABLE = "crawler_provider_calls";

type Insertable = Database["public"]["Tables"]["crawler_provider_calls"]["Insert"];

/**
 * What this module may write. `spent_on` is generated by the database, and this
 * `Omit` is the only compile-time guard that it is: the Supabase CLI's type
 * generator lists a `generated always … stored` column as an ordinary optional
 * insert column, so without this line the database refusal at runtime would be
 * the sole defence — on the write that records a call that has already left.
 */
export type CrawlerCallRow = Omit<Insertable, "id" | "spent_on">;

/** Only what this module actually calls, so a test can stand in for it. */
export type CrawlerCallDb = Pick<SupabaseClient<Database>, "from">;

/**
 * The day's spend, or why it could not be read — never a number and a reason
 * together. A `calls` that a caller could read out of a failed read is exactly
 * how an unmeasurable run starts anyway.
 */
export type SpendToday = { readonly ok: true; readonly calls: number } | { readonly ok: false; readonly reason: string };

/** What this run may spend, once the day is taken into account. */
export type DayBudget = {
  readonly ok: true;
  /** The effective ceiling: the smaller of the run's own and what is left of the day. */
  readonly ceiling: number;
  /** `DEFAULT_DAILY_ALLOWANCE` less the live reserve — the same headroom gate A already uses. */
  readonly dailyCap: number;
  readonly spentToday: number;
  readonly remainingToday: number;
  /** True when the DAY is the binding constraint, because an operator's next move differs. */
  readonly limitedByDay: boolean;
  readonly reason: string;
};

export type DayVerdict = DayBudget | { readonly ok: false; readonly reason: string };

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

function whole(value: number): number {
  return Number.isFinite(value) ? Math.max(0, Math.trunc(value)) : 0;
}

/**
 * How many calls this run may make, given what the day has already cost.
 *
 * **The daily cap is not a new number.** It is the same headroom the per-run
 * ceiling is built from — `DEFAULT_DAILY_ALLOWANCE` less the live reserve — so
 * one constant governs both gates and widening one cannot silently leave the
 * other behind.
 *
 * **It fails closed.** An unreadable count refuses the run rather than assuming
 * zero: a run nobody can measure is precisely the hazard this exists to remove,
 * and "the counter was down" is the one excuse that would let a scheduled
 * crawler spend a month.
 */
export function dayCeiling({ perRunCeiling, dailyCap, spent }: { readonly perRunCeiling: number; readonly dailyCap: number; readonly spent: SpendToday }): DayVerdict {
  if (!spent.ok) {
    return {
      ok: false,
      reason:
        `the crawler's spend for today could not be read, so this run cannot know what is left of the day's budget: ${spent.reason}. ` +
        "Nothing was asked. An unmeasurable run is the hazard the daily counter exists to remove, so it refuses rather than assuming the day is clean.",
    };
  }
  const cap = whole(dailyCap);
  const spentToday = whole(spent.calls);
  const remainingToday = Math.max(0, cap - spentToday);
  const perRun = whole(perRunCeiling);
  const ceiling = Math.min(perRun, remainingToday);
  const limitedByDay = remainingToday < perRun;
  const reason = limitedByDay
    ? `${ceiling} calls: ${remainingToday} left of today's ${cap}, ${spentToday} already spent today — below this run's own ceiling of ${perRun}`
    : `${ceiling} calls: this run's own ceiling, and today has ${remainingToday} of its ${cap} left (${spentToday} already spent)`;
  return { ok: true, ceiling, dailyCap: cap, spentToday, remainingToday, limitedByDay, reason };
}

/**
 * How many provider calls the crawler has already charged to `day`.
 *
 * `day` is an IST calendar date, and the column it filters on is generated by
 * the same expression `availability_observations.observed_on` uses, so the two
 * agree when read side by side.
 *
 * **A plain select with an exact count, never a HEAD request.** A HEAD has no
 * body for the client to read a refusal out of: a table that does not exist
 * answers 204 with `error: null`, and the gate would pass on a counter that
 * cannot be read at all. `crawl-availability.mjs`'s own store preflight learned
 * that the expensive way; this makes the same choice for the same reason.
 * `range(0, 0)` asks the server for the count and at most one row of body.
 */
export async function readCallsToday(db: CrawlerCallDb, day: string, options: { readonly signal?: AbortSignal } = {}): Promise<SpendToday> {
  if (!ISO_DATE.test(day)) return { ok: false, reason: `"${day}" is not an ISO date (yyyy-mm-dd), so there is no day to count` };
  try {
    let chain = db.from(CRAWLER_CALL_TABLE).select("id", { count: "exact" }).eq("spent_on", day);
    if (options.signal !== undefined) chain = chain.abortSignal(options.signal);
    const { error, count } = await chain.range(0, 0);
    if (error) return { ok: false, reason: `the crawler's spend ledger could not be read: ${error.message}` };
    // `count ?? 0` here is the silent version of the same failure: a store that
    // answers without a count would read as a clean day and free the whole ceiling.
    if (typeof count !== "number" || !Number.isInteger(count) || count < 0) {
      return { ok: false, reason: "the crawler's spend ledger answered without a count, which is not an unspent day but an unreadable one" };
    }
    return { ok: true, calls: count };
  } catch (cause) {
    return { ok: false, reason: `the crawler's spend ledger could not be read: ${cause instanceof Error ? cause.message : String(cause)}` };
  }
}

/**
 * Charges one provider call to the ledger.
 *
 * **Called before the call leaves, not after it returns.** A process killed
 * mid-run has still spent what it sent, and a counter that loses those calls is
 * worse than none: it under-reports exactly when something went wrong. Recording
 * first over-counts a call that never actually goes out, which is the safe
 * direction — this run spends less, never more.
 *
 * It returns a verdict rather than throwing, and the caller is expected to stop:
 * a call that cannot be recorded is a call the next run will not know about.
 */
export async function recordProviderCall(db: CrawlerCallDb, spentAt: string): Promise<{ readonly ok: true } | { readonly ok: false; readonly reason: string }> {
  const row: CrawlerCallRow = { spent_at: spentAt };
  try {
    const { error } = await db.from(CRAWLER_CALL_TABLE).insert([row]);
    if (error) return { ok: false, reason: `the call could not be charged to the crawler's daily budget: ${error.message}` };
    return { ok: true };
  } catch (cause) {
    return { ok: false, reason: `the call could not be charged to the crawler's daily budget: ${cause instanceof Error ? cause.message : String(cause)}` };
  }
}
