import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "@/types/supabase";
import type { AvailabilityAnswer, AvailabilityDayRecord, AvailabilityRequest } from "./availability-source";
import { log } from "./log";
import { createAdminSupabase } from "./supabase/admin";

// ---------------------------------------------------------------------------
// The observation store's writer: one row per day an availability answer
// returned, recorded so a Trakline confirmation model can later be fitted to
// what the source actually said.
//
// **No personal data reaches this module.** It takes an `AvailabilityRequest`
// and an `AvailabilityAnswer` and writes facts about berths — train, leg, class,
// quota, journey date, and where the waitlist stood. There is no PNR here, no
// user, no passenger. The table refuses one anyway (see the migration), but the
// rule starts here, where the row is built.
//
// **It never throws into a caller.** A failed insert loses an observation; a
// thrown insert would lose a traveller their answer. When the Pre-booking form
// ships this runs on the response path, so it is written that way now, while the
// only caller is a crawler, rather than after it matters.
// ---------------------------------------------------------------------------

export const OBSERVATION_TABLE = "availability_observations";

/**
 * The columns of `availability_observations_once_a_day_idx`, in its order. The
 * write resolves against that unique index, so a crawler retried after a partial
 * failure updates its row instead of double-counting it. A test binds this
 * string to the migration, because a typo here would only ever show in
 * production — PostgREST would reject the write and the observation would vanish
 * into a log line.
 */
export const OBSERVATION_CONFLICT_COLUMNS = "train_no,travel_class,quota,from_code,to_code,journey_date,observed_on";

type Insertable = Database["public"]["Tables"]["availability_observations"]["Insert"];

/**
 * What this module may write, which is deliberately less than the table holds.
 *
 * `days_out` and `observed_on` are generated by the database; the CLI's type
 * generator lists them as optional insert columns anyway, so removing them here
 * is the only compile-time guard there is. `seats`, `outcome` and `outcome_at`
 * are left out for a different reason: the write is an upsert, and every column
 * in the payload is overwritten on conflict. Keeping them out means a
 * re-observation later the same day can never wipe a resolved outcome.
 */
export type ObservationRow = Omit<Insertable, "id" | "days_out" | "observed_on" | "seats" | "outcome" | "outcome_at">;

/** Only what the module actually calls, so a test can stand in for it. */
export type ObservationDb = Pick<SupabaseClient<Database>, "from">;

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

/** Station codes, class and quota are compared case-insensitively upstream; storing one casing keeps `sl` and `SL` from becoming two observations of the same berth. */
function normalised(value: string): string {
  return value.trim().toUpperCase();
}

function rowFor(request: AvailabilityRequest, answer: AvailabilityAnswer, day: AvailabilityDayRecord): ObservationRow {
  return {
    // The moment the source answered, not the moment this row is written: it is
    // what `days_out` and `observed_on` are computed from, and re-recording the
    // same answer must land on the same row.
    observed_at: answer.retrievedAt,
    train_no: request.trainNo.trim(),
    from_code: normalised(request.from),
    to_code: normalised(request.to),
    travel_class: normalised(request.travelClass),
    quota: normalised(request.quota),
    // The day's own date, never the date that was asked for: one call returns a
    // four-date window and each date is its own observation.
    journey_date: day.date,
    status: day.status,
    raw_status: day.rawStatus,
    wl_booking: day.wlBooking,
    wl_current: day.wlCurrent,
    // Recorded privately as the baseline a Trakline model has to beat. Never rendered.
    source_prediction: day.prediction,
    source_prediction_pct: day.predictionPercentage,
  };
}

/**
 * One row per returned day. Pure, so the shape of what gets written is testable
 * without a database.
 *
 * Two days carrying the same date would collide on the unique index inside a
 * single statement, which Postgres refuses outright — losing the whole batch
 * rather than the duplicate. So a repeated date keeps its last reading, matching
 * the upsert's own rule. A date that is not ISO is dropped for the same reason:
 * one unusable value should cost one observation, not four.
 */
export function observationRows(request: AvailabilityRequest, answer: AvailabilityAnswer): readonly ObservationRow[] {
  const byDate = new Map<string, AvailabilityDayRecord>();
  for (const day of answer.days) {
    if (ISO_DATE.test(day.date)) byDate.set(day.date, day);
  }
  return [...byDate.values()].map((day) => rowFor(request, answer, day));
}

/**
 * Records what availability said. Returns how many rows it wrote, and `0` for
 * every failure — a missing secret key, a refused write, a network fault. It
 * never throws.
 */
export async function recordObservations(request: AvailabilityRequest, answer: AvailabilityAnswer, db?: ObservationDb): Promise<number> {
  const rows = observationRows(request, answer);
  if (rows.length === 0) return 0;
  try {
    const client = db ?? createAdminSupabase();
    const { error } = await client
      .from(OBSERVATION_TABLE)
      // `ignoreDuplicates: false` is the decision, stated: the later read of the
      // same IST day is the more current fact about those berths, and a retry
      // after a partial failure is exactly when the newer answer is the one worth
      // keeping.
      .upsert([...rows], { onConflict: OBSERVATION_CONFLICT_COLUMNS, ignoreDuplicates: false });
    if (error) {
      log.warn("availability observations not recorded", { train: rows[0]?.train_no, rows: rows.length, reason: error.message });
      return 0;
    }
    return rows.length;
  } catch (cause) {
    log.warn("availability observations not recorded", { train: rows[0]?.train_no, rows: rows.length, cause });
    return 0;
  }
}
