import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { BAKE_SOURCES, SHAPES, contentHash, manifestSource, partsOf, shapeSvg, sourceHash } from "../../../scripts/bake/emit.mjs";

const PATHS = { "shell|line": "M0 0l1 0", "shell|faint": "M2 2l0 1", "coach|line": "M5 5l1 1", "world|near": "M9 9l1 0" };

describe("writing a baked shape", () => {
  it("names the four shapes with their sizes", () => {
    expect(Object.keys(SHAPES)).toEqual(["anatomyWide", "anatomyTall", "terminusWide", "terminusTall"]);
    expect(SHAPES.anatomyWide).toEqual({ kind: "anatomy", W: 1800, H: 900, file: "anatomy-wide" });
    expect(SHAPES.terminusTall).toEqual({ kind: "terminus", W: 1100, H: 900, file: "terminus-tall" });
  });

  it("gathers each part's paths into one group, in a stable order", () => {
    expect(partsOf(PATHS)).toEqual(["coach", "shell", "world"]);
  });

  it("draws in currentColor, each weight a variable the page can set, with no script or link", () => {
    const svg = shapeSvg(PATHS);
    expect(svg).toContain('<g id="shell" fill="none" stroke="currentColor"');
    expect(svg).toContain('<path d="M0 0l1 0" vector-effect="non-scaling-stroke" style="stroke-opacity:var(--still-line,.8)"/>');
    expect(svg).toContain("stroke-opacity:var(--still-faint,.14)");
    expect(svg).toContain("stroke-opacity:var(--still-near,.42)");
    expect(svg).not.toMatch(/<script|href=|\son\w+=/);
    expect(svg.startsWith('<svg xmlns="http://www.w3.org/2000/svg"><defs>')).toBe(true);
  });

  it("hashes content into a short, stable name", () => {
    expect(contentHash("a")).toMatch(/^[0-9a-f]{10}$/);
    expect(contentHash("a")).toBe(contentHash("a"));
    expect(contentHash("a")).not.toBe(contentHash("b"));
  });

  it("hashes the scene sources, so a changed source asks for a new bake", () => {
    const root = mkdtempSync(join(tmpdir(), "bake-"));
    writeFileSync(join(root, "a.ts"), "one");
    writeFileSync(join(root, "b.ts"), "two");
    const before = sourceHash(root, ["a.ts", "b.ts"], "0.186.0");
    expect(before).toMatch(/^[0-9a-f]{16}$/);
    writeFileSync(join(root, "b.ts"), "two\r\n");
    const crlf = sourceHash(root, ["a.ts", "b.ts"], "0.186.0");
    writeFileSync(join(root, "b.ts"), "two\n");
    expect(sourceHash(root, ["a.ts", "b.ts"], "0.186.0")).toBe(crlf); // line endings never ask for a re-bake
    writeFileSync(join(root, "b.ts"), "three");
    expect(sourceHash(root, ["a.ts", "b.ts"], "0.186.0")).not.toBe(before);
  });

  it("writes still-manifest.ts as typed, generated data", () => {
    const text = manifestSource({ sourceHash: "abc", shapes: { anatomyWide: { href: "/journey/anatomy-wide.0123456789.svg", viewBox: [0, 0, 10, 5], parts: ["shell"], anchors: { shell: [1, 2] } } } });
    expect(text).toContain("Generated by scripts/bake-train-stills.mjs");
    expect(text).toContain('import type { StillManifest } from "./still-shapes";');
    expect(text).toContain("as const satisfies StillManifest;");
    expect(text).toContain('"href": "/journey/anatomy-wide.0123456789.svg"');
  });

  it("hashes three's version too, and counts the bake's own driver among its sources", () => {
    expect(BAKE_SOURCES).toContain("scripts/bake-train-stills.mjs");
    const root = mkdtempSync(join(tmpdir(), "bake-"));
    writeFileSync(join(root, "a.ts"), "one");
    mkdirSync(join(root, "node_modules/three"), { recursive: true });
    writeFileSync(join(root, "node_modules/three/package.json"), JSON.stringify({ version: "0.186.0" }));
    const before = sourceHash(root, ["a.ts"]);
    expect(before).toBe(sourceHash(root, ["a.ts"], "0.186.0"));
    writeFileSync(join(root, "node_modules/three/package.json"), JSON.stringify({ version: "0.187.0" }));
    expect(sourceHash(root, ["a.ts"])).not.toBe(before);
  });

  it("refuses a path keyed with no known line class", () => {
    expect(() => shapeSvg({ "shell|bold": "M0 0l1 0" })).toThrow(/line class/);
    expect(() => shapeSvg({ shell: "M0 0l1 0" })).toThrow(/line class/);
  });
});
