// The bake's writing half (spec §3.D): each baked shape as its own SVG file (J4-2), one <g id> per part, strokes in
// currentColor and each ink weight a CSS variable the page sets (J4-3); the file's content hash for its name; the
// scene sources' hash, so a changed source asks for a new bake; and still-manifest.ts. Pure; the bake script does
// the writing.
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";

export const SHAPES = {
  anatomyWide: { kind: "anatomy", W: 1800, H: 900, file: "anatomy-wide" },
  anatomyTall: { kind: "anatomy", W: 900, H: 1200, file: "anatomy-tall" },
  terminusWide: { kind: "terminus", W: 2100, H: 660, file: "terminus-wide" },
  terminusTall: { kind: "terminus", W: 1100, H: 900, file: "terminus-tall" },
};

/** What a still is drawn from. Change one and the stills must be baked again (tests/unit/scripts/bake-stills.test.ts). */
export const BAKE_SOURCES = [
  "src/components/landing/journey/pose.ts",
  "src/components/landing/journey/train-parts.ts",
  "src/components/landing/journey/scene/math.ts",
  "src/components/landing/journey/scene/util.ts",
  "src/components/landing/journey/scene/lines.ts",
  "src/components/landing/journey/scene/rig-parts.ts",
  "src/components/landing/journey/scene/rig.ts",
  "src/components/landing/journey/scene/line-world.ts",
  "src/components/landing/journey/scene/world.ts",
  "src/components/landing/journey/scene/apply-pose.ts",
  "scripts/bake/trace.ts",
  "scripts/bake/page.ts",
  "scripts/bake/emit.mjs",
  "scripts/bake-train-stills.mjs",
];

/** @param {string} root */
export function threeVersion(root) {
  return JSON.parse(readFileSync(join(root, "node_modules/three/package.json"), "utf8")).version;
}

/** @param {string} root @param {readonly string[]} [files] @param {string} [three] */
export function sourceHash(root, files = BAKE_SOURCES, three = threeVersion(root)) {
  const hash = createHash("sha256");
  hash.update(`three@${three}\0`);
  for (const file of files) hash.update(`${file}\0${readFileSync(join(root, file), "utf8").replace(/\r\n/g, "\n")}\0`);
  return hash.digest("hex").slice(0, 16);
}

/** @param {string} text */
export function contentHash(text) {
  return createHash("sha256").update(text).digest("hex").slice(0, 10);
}

/** @param {Record<string, string>} paths keyed "part|class" */
export function partsOf(paths) {
  return [...new Set(Object.keys(paths).map((key) => key.split("|")[0]))].sort();
}

const WEIGHT = { line: "var(--still-line,.8)", faint: "var(--still-faint,.14)", near: "var(--still-near,.42)" };

/** @param {string} key */
function classOf(key) {
  const [part, cls] = key.split("|");
  if (!part || cls === undefined || !Object.hasOwn(WEIGHT, cls)) throw new Error(`shapeSvg: "${key}" names no line class (line, faint or near)`);
  return cls;
}

/** @param {Record<string, string>} paths keyed "part|class" */
export function shapeSvg(paths) {
  const groups = partsOf(paths).map((part) => {
    const body = Object.keys(paths)
      .filter((key) => key.split("|")[0] === part)
      .sort()
      .map((key) => `<path d="${paths[key]}" vector-effect="non-scaling-stroke" style="stroke-opacity:${WEIGHT[classOf(key)]}"/>`)
      .join("");
    return `<g id="${part}" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round">${body}</g>`;
  });
  return `<svg xmlns="http://www.w3.org/2000/svg"><defs>${groups.join("")}</defs></svg>\n`;
}

/** @param {{ sourceHash: string, shapes: Record<string, unknown> }} manifest */
export function manifestSource(manifest) {
  return `// Generated by scripts/bake-train-stills.mjs from the scene sources it hashed. Do not edit: run npm run bake:stills.
import type { StillManifest } from "./still-shapes";

export const STILL_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const satisfies StillManifest;
`;
}
