// Generated by scripts/bake-train-stills.mjs from the scene sources it hashed. Do not edit: run npm run bake:stills.
import type { StillManifest } from "./still-shapes";

export const STILL_MANIFEST = {
  "sourceHash": "22819ad7c64465d3",
  "shapes": {
    "anatomyWide": {
      "href": "/journey/anatomy-wide.f3d026ef40.svg",
      "viewBox": [
        0,
        0,
        821.5,
        524.5
      ],
      "parts": [
        "bogieFront",
        "bogieRear",
        "cabFront",
        "cabRear",
        "pantoFront",
        "pantoRear",
        "roof",
        "shell",
        "tanks",
        "wheelsFront",
        "wheelsRear",
        "world"
      ],
      "anchors": {
        "pantoFront": [
          575,
          65.5
        ],
        "shell": [
          449,
          228.5
        ],
        "cabFront": [
          752.5,
          231
        ],
        "bogieFront": [
          532,
          393.5
        ],
        "wheelsFront": [
          562.5,
          477
        ],
        "pantoRear": [
          198,
          34
        ],
        "roof": [
          293.5,
          101.5
        ],
        "cabRear": [
          59.5,
          180
        ],
        "bogieRear": [
          218,
          342
        ],
        "wheelsRear": [
          184,
          407.5
        ]
      }
    },
    "anatomyTall": {
      "href": "/journey/anatomy-tall.5b4bce8627.svg",
      "viewBox": [
        0,
        0,
        765,
        489.5
      ],
      "parts": [
        "bogieFront",
        "bogieRear",
        "cabFront",
        "cabRear",
        "pantoFront",
        "pantoRear",
        "roof",
        "shell",
        "tanks",
        "wheelsFront",
        "wheelsRear",
        "world"
      ],
      "anchors": {
        "pantoFront": [
          534.5,
          59
        ],
        "shell": [
          415.5,
          212
        ],
        "cabFront": [
          702,
          214.5
        ],
        "bogieFront": [
          493.5,
          366.5
        ],
        "wheelsFront": [
          522,
          444.5
        ],
        "pantoRear": [
          181.5,
          31.5
        ],
        "roof": [
          271,
          94
        ],
        "cabRear": [
          55,
          167.5
        ],
        "bogieRear": [
          201,
          317.5
        ],
        "wheelsRear": [
          169.5,
          378
        ]
      }
    },
    "terminusWide": {
      "href": "/journey/terminus-wide.fd3dd93480.svg",
      "viewBox": [
        0,
        0,
        1728,
        292
      ],
      "parts": [
        "bogieFront",
        "bogieRear",
        "cabFront",
        "cabRear",
        "coach",
        "pantoFront",
        "pantoRear",
        "roof",
        "shell",
        "tanks",
        "wheelsFront",
        "wheelsRear",
        "world"
      ],
      "anchors": {}
    },
    "terminusTall": {
      "href": "/journey/terminus-tall.513e76bca8.svg",
      "viewBox": [
        0,
        0,
        1100,
        329
      ],
      "parts": [
        "bogieFront",
        "bogieRear",
        "cabRear",
        "coach",
        "pantoFront",
        "pantoRear",
        "roof",
        "shell",
        "tanks",
        "wheelsFront",
        "wheelsRear",
        "world"
      ],
      "anchors": {}
    }
  }
} as const satisfies StillManifest;
