"use client";

// Fluent icons are client-only modules. Re-exporting them from a client
// boundary lets server components reference them as client components.
export {
  ArrowLeftRegular,
  ArrowRightRegular,
  BookmarkRegular,
  BookmarkFilled,
  CalendarClockRegular,
  CheckmarkRegular,
  ChevronDownRegular,
  CopyRegular,
  DesktopRegular,
  DismissRegular,
  ErrorCircleRegular,
  GaugeRegular,
  InfoRegular,
  PersonRegular,
  ArrowSyncRegular,
  ShareRegular,
  SignOutRegular,
  TicketDiagonalRegular,
  WarningRegular,
  WeatherMoonRegular,
  WeatherSunnyRegular,
  ArrowDownloadRegular,
  DeleteRegular,
  ArrowExportRegular,
  EyeTrackingRegular,
  DatabaseRegular,
  DocumentTableRegular,
  FlowchartRegular,
  QuestionCircleRegular,
  RoadRegular,
  // The row-menu dots. Filled, not Regular, because ConsoleTeam.dc.html:145 draws three solid
  // circles (`fill="currentColor"`, r=1.25) rather than three outlines.
  MoreHorizontalFilled,
  // Filled: the navigation set (masthead, footer sections, theme cells, sign in)
  CalendarClockFilled,
  DarkThemeFilled,
  DismissFilled,
  EyeFilled,
  GaugeFilled,
  LineHorizontal3Filled,
  PersonFilled,
  TicketDiagonalFilled,
  WeatherMoonFilled,
  WeatherSunnyFilled,
} from "@fluentui/react-icons";
